from enum import StrEnum


class ArticleStatus(StrEnum):
    COLLECTED = "COLLECTED"
    CLEANED = "CLEANED"
    DUPLICATE_CANDIDATE = "DUPLICATE_CANDIDATE"
    DUPLICATE_CONFIRMED = "DUPLICATE_CONFIRMED"
    EXTRACTION_PENDING = "EXTRACTION_PENDING"
    EXTRACTED = "EXTRACTED"
    LINKING_PENDING = "LINKING_PENDING"
    LINKED = "LINKED"
    VERIFICATION_PENDING = "VERIFICATION_PENDING"
    VERIFIED_PARTIAL = "VERIFIED_PARTIAL"
    ISSUE_ASSIGNED = "ISSUE_ASSIGNED"
    ARCHIVED = "ARCHIVED"
    FAILED = "FAILED"


class EntityLinkingStatus(StrEnum):
    LINKED = "LINKED"
    PROVISIONAL_LINK = "PROVISIONAL_LINK"
    AMBIGUOUS = "AMBIGUOUS"
    UNRESOLVED = "UNRESOLVED"
    NEW_ENTITY_CANDIDATE = "NEW_ENTITY_CANDIDATE"
    MERGE_CANDIDATE = "MERGE_CANDIDATE"
    NEEDS_HUMAN_REVIEW = "NEEDS_HUMAN_REVIEW"


class EntityStatus(StrEnum):
    ACTIVE = "ACTIVE"
    NEEDS_HUMAN_REVIEW = "NEEDS_HUMAN_REVIEW"


class SourceType(StrEnum):
    NEWS = "news"
    OFFICIAL = "official"
    REPORT = "report"
    BLOG = "blog"
    OTHER = "other"


class FactStatus(StrEnum):
    EXTRACTED = "EXTRACTED"
    NORMALIZED = "NORMALIZED"
    VERIFICATION_PENDING = "VERIFICATION_PENDING"
    VERIFIED = "VERIFIED"
    PARTIALLY_VERIFIED = "PARTIALLY_VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    DISPUTED = "DISPUTED"
    CONTRADICTED = "CONTRADICTED"
    TIMEFRAME_UNCLEAR = "TIMEFRAME_UNCLEAR"
    NUMBER_MISMATCH = "NUMBER_MISMATCH"
    SOURCE_CONFLICT = "SOURCE_CONFLICT"
    DEPRECATED = "DEPRECATED"
    RETRACTED = "RETRACTED"
    NEEDS_HUMAN_REVIEW = "NEEDS_HUMAN_REVIEW"


class ClaimStatus(StrEnum):
    EXTRACTED = "EXTRACTED"
    ATTRIBUTED = "ATTRIBUTED"
    SOURCE_IDENTIFIED = "SOURCE_IDENTIFIED"
    INCENTIVE_ANALYZED = "INCENTIVE_ANALYZED"
    SUPPORTED_BY_SOURCE = "SUPPORTED_BY_SOURCE"
    WEAKLY_SUPPORTED = "WEAKLY_SUPPORTED"
    DISPUTED = "DISPUTED"
    SPECULATIVE = "SPECULATIVE"
    NEEDS_CONTEXT = "NEEDS_CONTEXT"
    NEEDS_HUMAN_REVIEW = "NEEDS_HUMAN_REVIEW"


class EventStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    CONFIRMED = "CONFIRMED"
    MERGED = "MERGED"
    SPLIT_REQUIRED = "SPLIT_REQUIRED"
    RELATED_TO_EXISTING = "RELATED_TO_EXISTING"
    ARCHIVED = "ARCHIVED"
    NEEDS_REVIEW = "NEEDS_REVIEW"


class IssueStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    ACTIVE = "ACTIVE"
    DEVELOPING = "DEVELOPING"
    STABLE = "STABLE"
    UPDATED = "UPDATED"
    DISPUTED = "DISPUTED"
    ARCHIVED = "ARCHIVED"
    NEEDS_EDITOR_REVIEW = "NEEDS_EDITOR_REVIEW"


class PerspectiveStatus(StrEnum):
    SUPPORTED_VIEW = "SUPPORTED_VIEW"
    PLAUSIBLE_VIEW = "PLAUSIBLE_VIEW"
    MINORITY_VIEW = "MINORITY_VIEW"
    SPECULATIVE_VIEW = "SPECULATIVE_VIEW"
    LOW_EVIDENCE_VIEW = "LOW_EVIDENCE_VIEW"
    EXCLUDED_VIEW = "EXCLUDED_VIEW"


class ReportStatus(StrEnum):
    DRAFT = "DRAFT"
    EVIDENCE_CHECKED = "EVIDENCE_CHECKED"
    COUNTERARGUMENT_CHECKED = "COUNTERARGUMENT_CHECKED"
    BALANCE_CHECKED = "BALANCE_CHECKED"
    EDITOR_REVIEW_PENDING = "EDITOR_REVIEW_PENDING"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    UPDATED = "UPDATED"
    CORRECTED = "CORRECTED"
    RETRACTED = "RETRACTED"


class ReviewStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVISION_REQUESTED = "REVISION_REQUESTED"


class ReviewTargetType(StrEnum):
    MENTION = "mention"
    FACT = "fact"
    CLAIM = "claim"
    REPORT = "report"
