from enum import StrEnum


class ArticleStatus(StrEnum):
    COLLECTED = "COLLECTED"
    CLEANED = "CLEANED"
    DUPLICATE_CANDIDATE = "DUPLICATE_CANDIDATE"
    DUPLICATE_CONFIRMED = "DUPLICATE_CONFIRMED"
    EXTRACTION_PENDING = "EXTRACTION_PENDING"
    EXTRACTED = "EXTRACTED"
    LINKING_PENDING = "LINKING_PENDING"
    LINKED = "LINKED"
    VERIFICATION_PENDING = "VERIFICATION_PENDING"
    VERIFIED_PARTIAL = "VERIFIED_PARTIAL"
    ISSUE_ASSIGNED = "ISSUE_ASSIGNED"
    ARCHIVED = "ARCHIVED"
    FAILED = "FAILED"


class EntityLinkingStatus(StrEnum):
    LINKED = "LINKED"
    PROVISIONAL_LINK = "PROVISIONAL_LINK"
    AMBIGUOUS = "AMBIGUOUS"
    UNRESOLVED = "UNRESOLVED"
    NEW_ENTITY_CANDIDATE = "NEW_ENTITY_CANDIDATE"
    MERGE_CANDIDATE = "MERGE_CANDIDATE"
    NEEDS_HUMAN_REVIEW = "NEEDS_HUMAN_REVIEW"


class EntityStatus(StrEnum):
    ACTIVE = "ACTIVE"
    NEEDS_HUMAN_REVIEW = "NEEDS_HUMAN_REVIEW"


class SourceType(StrEnum):
    NEWS = "news"
    OFFICIAL = "official"
    REPORT = "report"
    BLOG = "blog"
    OTHER = "other"

